<?php

// Block Background Colors
$block_background_colors = array (
	'white' => 'White',
	'dark' => 'Blue',
	'darker' => 'Dark Blue',
	'lightest' => 'Light Gray',
	'none' => 'None',
	'image' => 'Image'
);


if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_content-blocks',
		'title' => 'Content Blocks',
		'fields' => array (
			array (
				'key' => 'field_1000000000001',
				'label' => 'Content Blocks',
				'name' => 'blocks',
				'type' => 'flexible_content',
				'layouts' => array (
					array (
						'label' => 'Heading',
						'name' => 'heading',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_1000000000002',
								'label' => 'Background',
								'name' => 'block_background',
								'type' => 'select',
								'column_width' => '',
								'choices' => $block_background_colors,
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_1000000000003',
								'label' => 'Background Image',
								'name' => 'block_background_image',
								'type' => 'image',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000002',
											'operator' => '==',
											'value' => 'image',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_1000000000004',
								'label' => 'Heading',
								'name' => 'heading',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_1000000000005',
								'label' => 'Center Text',
								'name' => 'center',
								'type' => 'true_false',
								'message' => '',
								'default_value' => 0,
							),
						),
					),
					array (
						'label' => 'HTML',
						'name' => 'html',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_1000000000006',
								'label' => 'Background',
								'name' => 'block_background',
								'type' => 'select',
								'column_width' => '',
								'choices' => $block_background_colors,
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_1000000000007',
								'label' => 'Background Image',
								'name' => 'block_background_image',
								'type' => 'image',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000006',
											'operator' => '==',
											'value' => 'image',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_1000000000008',
								'label' => 'HTML Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'default_value' => '',
								'toolbar' => 'full',
								'media_upload' => 'yes',
							),
						),
					),
					array (
						'label' => 'Button',
						'name' => 'button',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_1000000000009',
								'label' => 'Background',
								'name' => 'block_background',
								'type' => 'select',
								'column_width' => '',
								'choices' => $block_background_colors,
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_1000000000010',
								'label' => 'Background Image',
								'name' => 'block_background_image',
								'type' => 'image',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000009',
											'operator' => '==',
											'value' => 'image',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_1000000000011',
								'label' => 'Button Type',
								'name' => 'button_type',
								'type' => 'select',
								'column_width' => '',
								'choices' => array (
									'page' => 'Page',
									'link' => 'Link',
								),
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_1000000000012',
								'label' => 'Button Text',
								'name' => 'button_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_1000000000013',
								'label' => 'Button Link',
								'name' => 'button_link',
								'type' => 'text',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000011',
											'operator' => '==',
											'value' => 'link',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'http://',
								'prepend' => '',
								'append' => '',
								'formatting' => 'none',
								'maxlength' => '',
							),
							array (
								'key' => 'field_1000000000014',
								'label' => 'Button Page',
								'name' => 'button_page',
								'type' => 'page_link',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000008',
											'operator' => '==',
											'value' => 'page',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'post_type' => array (
									0 => 'post',
									1 => 'page',
									2 => 'product',
									3 => 'locations',
									4 => 'resources',
								),
								'allow_null' => 0,
								'multiple' => 0,
							),
						),
					),
					array (
						'label' => 'Testimonials',
						'name' => 'testimonials',
						'display' => 'row',
						'min' => '',
						'max' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_1000000000015',
								'label' => 'Background',
								'name' => 'block_background',
								'type' => 'select',
								'column_width' => '',
								'choices' => $block_background_colors,
								'default_value' => '',
								'allow_null' => 0,
								'multiple' => 0,
							),
							array (
								'key' => 'field_1000000000016',
								'label' => 'Background Image',
								'name' => 'block_background_image',
								'type' => 'image',
								'conditional_logic' => array (
									'status' => 1,
									'rules' => array (
										array (
											'field' => 'field_1000000000015',
											'operator' => '==',
											'value' => 'image',
										),
									),
									'allorany' => 'all',
								),
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'medium',
								'library' => 'all',
							),
							array (
								'key' => 'field_1000000000017',
								'label' => 'Testimonials',
								'name' => 'testimonials',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_1000000000018',
										'label' => 'Testimonial',
										'name' => 'testimonial',
										'type' => 'textarea',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'formatting' => 'none',
									),
									array (
										'key' => 'field_1000000000019',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '(Optional)',
										'column_width' => '',
										'save_format' => 'object',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
									array (
										'key' => 'field_1000000000020',
										'label' => 'Attribution',
										'name' => 'attribution',
										'type' => 'text',
										'instructions' => '(Optional)',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'none',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'row',
								'button_label' => 'Add Testimonial',
							),
						),
					),
				),
				'button_label' => 'Add Content',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 100,
	));
}
